---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyr)
library(tidyverse)
library(janitor)
```

```{r}
#Question 1
#Read in all 4 credit card transaction datasets and clean column names.

card_base <- read_csv("data/CardBase.csv") %>% clean_names()
cust_base <- read_csv("data/CustomerBase.csv") %>% clean_names()
fraud_base <- read_csv("data/FraudBase.csv") %>% clean_names()
transac_base <- read_csv("data/TransactionBase.csv") %>% clean_names()
```


```{r}
#Question 2

#Join the data containing card details and customer details by customer id, so that all records of card details and any matching records in customer details are kept. Before you run the code, think about how many rows you expect to see after joining.

left_join(card_base, cust_base, by = "cust_id")
```
```{r}
#Question 3

#Join the data containing fraud details with transaction details so all rows of both tables are kept. What does the resulting row number tell you?

full_join(fraud_base, transac_base, by = "transaction_id")

```
```{r}
#Question 4

#Join the data containing card details with transaction details so rows from the first which have matching ones in the second are returned.

inner_join(card_base,transac_base, by = c("card_number" = "credit_card_id"))

```
```{r}
#Question 5

#Read in hat_observations and separate observation into two columns, hat_colour and hat_type

hat_observation <- read_csv("data/hat_observations.csv") 

hat_observation_f <- hat_observation %>% 
  separate(
    col = observation,
    into = c("hat_colour", "hat_type"),
    sep = ","
  ) 
  hat_observation_f
  
  
```



```{r}

#Question 6

#Unite day, month, and year columns into a column called date using a suitable separator. Then find the date where the most berets were observed.

hat_observation_final <- hat_observation_f %>% 
  unite(
    col = date,
      c(day, month, year),
    sep = "-"
  )  %>% 
  select(date, hat_type, observation_count) %>% 
  filter(hat_type == "beret") %>% 
  slice_max(observation_count, n = 1)
  
hat_observation_final
```

```{r}
#or this code will work for above too

#hat_observations_date <- hat_observations %>% 
 # unite("date", day:year, sep = "-") 

#hat_observations_date %>% 
 # filter(hat_type == "beret") %>% 
  #group_by(date) %>% 
  #summarise(total = sum(observation_count)) %>% 
  #slice_max(total)
#OR
#hat_observations %>% 
 #group_by (year,month,day, hat_type) %>% 
  #summarise(total = sum(observation_count)) %>% 
  #arrange (desc(total))

```


```{r}
#hat_observation_final %>% 
 # select(date, hat_type, observation_count) %>% 
  #filter(hat_type == "beret") %>% 
  #slice_max(observation_count, n = 1)
  
```



```{r}

# Extension
#2.1 Joins
#Question 1

#Can you join all 4 datasets together so that you’re left with a dataset that looks like below with 109 rows and 12 columns?


#joining cust_base and card_base
cust_n_card <- inner_join(card_base,cust_base, by = "cust_id")
cust_n_card

```
```{r}

#contd...
#joining transac_base and fraud_base

transac_n_fraud <- inner_join(transac_base,fraud_base, by = "transaction_id")
transac_n_fraud
```
```{r}
#contd...
#joining cust_n_card and transac_n_fraud

inner_join(
  cust_n_card,
  transac_n_fraud, 
  by = c("card_number" = "credit_card_id")
          )
```
```{r}
#Extension
#2.2 tidyr
#Question 2

#Read in exam_scores and transform it into long format with two new columns exam_question and score. Then, using separate and select, remove superfluous information from the values in exam_question

exam_scores <- read_csv("data/exam_scores.csv")
exam_scores

```
```{r}
exam_scores %>% 
pivot_longer(
    cols = starts_with("e"),
    names_to = "exam_question","score", 
    values_to = "score"
) %>% 
  separate(
    col = exam_question,
    into =  c("unwanted", "exam_question"),
    sep = "_"
  ) %>% 
  select(-unwanted)

```

