---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(janitor)
```
<h1> Reading data
```{r}
last_five_cancer <- read_csv("data/5 Year Summary of Incidence by Health Board.csv") %>% 
  clean_names()

last_five_cancer
```


```{r}
last_five_cancer_borders
```


```{r}
last_five_cancer_borders <- last_five_cancer %>% 
  filter(hb == "S08000016")

last_five_cancer_borders
```

```{r}
unique(last_five_cancer_borders$year)
```
```{r}
last_five_cancer_borders %>% 
  ggplot() +
  aes(x = sex, y = incidences_all_ages, fill = sex)+
  geom_col(width = 0.5)
```

```{r}
incidence_hb <- read_csv("data/Incidence by Health Board.csv") %>% 
  clean_names()
incidence_hb
```

```{r}
incidence_hb_2014_2019 <- incidence_hb %>% 
  filter(year<2021 & year > 2014,
         hb == "S08000016")
  
incidence_hb_2014_2019
```

```{r}
incidence_hb_2014_2019 %>% 
  ggplot()+
  aes(x = year, y = incidences_all_ages, fill = "black")+
  geom_col(width = 0.5)
 
```



```{r}
mortality_hb <- read_csv("data/Mortality by Health Board.csv") %>% 
  clean_names()

mortality_hb
```

```{r}
mortality_hb_2014_2019 <- mortality_hb %>% 
  filter(year < 2021 & year > 2014,
         hbr == "S08000016")
  
mortality_hb_2014_2019
```

```{r}
mortality_hb_2014_2019 %>% 
  ggplot()+
  aes(x = year, y = deaths_all_ages)+
  geom_col(width = 0.5)
```


```{r}
wait_time_31 <- read_csv("data/Cancer Wait Time - 31 Day Standard.csv") %>% 
  clean_names()

wait_time_31

```

```{r}
unique(wait_time_31$quarter)
```



```{r}
wait_time_31_years <- wait_time_31 %>% 
  filter(hb == "S08000016") %>% 
  mutate(year  = case_when(quarter %in% c("2012Q1", "2012Q2", "2012Q3", "2012Q4") ~ 2012,
                           quarter %in% c("2013Q1", "2013Q2", "2013Q3", "2013Q4") ~ 2013,
                           quarter %in% c("2014Q1", "2014Q2", "2014Q3", "2014Q4") ~ 2014,
                           quarter %in% c("2015Q1", "2015Q2", "2015Q3", "2015Q4") ~ 2015,
                           quarter %in% c("2016Q1", "2016Q2", "2016Q3", "2016Q4") ~ 2016,
                           quarter %in% c("2017Q1", "2017Q2", "2017Q3", "2017Q4") ~ 2017,
                           quarter %in% c("2018Q1", "2018Q2", "2018Q3", "2018Q4") ~ 2018,
                           quarter %in% c("2019Q1", "2019Q2", "2019Q3", "2019Q4") ~ 2019,
                           quarter %in% c("2020Q1", "2020Q2", "2020Q3", "2020Q4") ~ 2020)
         , .after = "quarter")

wait_time_31_years
```
```{r}
wait_time_31_years %>% 
  arrange(number_of_eligible_referrals_treated_within31days, desc = TRUE)
  
```


```{r}
wait_time_31_years %>% 
  ggplot()+
  aes(x = year, y = number_of_eligible_referrals_treated_within31days)+
  geom_col()

```

```{r}
mortality_hb <- read_csv("data/Mortality by Health Board.csv") %>% 
  clean_names()

mortality_hb
```
```{r}
test1 <- mortality_hb %>% 
  filter(year <= 2021 & year >= 2010,
         hbr == "S08000016",
         sex == "Male" | sex == "Female",
         cancer_site != "All cancer types" & cancer_site != "All cancer types incl NMSC")
test1
  
```

```{r}
test1 %>% 
  ggplot()+
  aes(x = year, y = deaths_all_ages )+
  geom_col()
```

```{r}
test1 %>% 
  group_by(year) %>% 
  summarise(death_count = sum(deaths_all_ages))
  
```

