---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
incidence_hb <- read_csv("data/Incidence by Health Board.csv") %>% 
  clean_names()
incidence_hb
```
```{r}
unique(incidence_hb$year)
```

<h2> Cancer Incidences HB
<br>

```{r}
incidence_hb_2010_2021 <- incidence_hb %>% 
  filter(year <= 2021 & year >= 2010,
         hb == "S08000016",
         cancer_site == "All cancer types")
  
incidence_hb_2010_2021
```

```{r}
unique(incidence_hb_2010_2021 $incidences_all_ages)
```


```{r}
incidence_hb_2010_2021 %>% 
  ggplot()+
  aes(x = year, y = incidences_all_ages, colour = sex)+
  geom_point()+
  geom_line()+
  labs(
  title = "Cancer Incidences for all Cancer Types (2010 - 2021)",
  subtitle = "NHS Borders",
  ylab = "Cancer Incidences (All ages)")+
  scale_x_continuous(name = "Year", breaks = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019))+
  scale_y_continuous("Cancer Incidences (All ages)", limits = c(0,1000), breaks = c(100,200,300,400, 500,600,700,800,900,1000))
  
 
```
<br>

<h2> Mortality

<br>
```{r}
mortality_hb <- read_csv("data/Mortality by Health Board.csv") %>% 
  clean_names()

mortality_hb
```
```{r}
mortality_hb_2010_2021 <- mortality_hb %>% 
  filter(year <= 2021 & year >= 2010,
         hbr == "S08000016",
         cancer_site == "All cancer types",
         sex == "Male" | sex == "Female")
  
mortality_hb_2010_2021
```

```{r}
mortality_hb_2010_2021 %>% 
  group_by(year) %>% 
  summarise(death_count = sum(deaths_all_ages))
```


<br>
```{r}
mortality_hb_2010_2021 %>% 
  ggplot()+
  aes(x = year, y = deaths_all_ages, colour = sex)+
  geom_point()+
  geom_line()+
  labs(
  title = "Death for all Cancer Types (2010 - 2021)",
  subtitle = "NHS Borders")+
  scale_x_continuous(name = "Year", breaks = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019))+
  scale_y_continuous("Deaths (All ages)", limits = c(0,500), breaks = c(100,200,300,400, 500))
  
 
```
<br>



```{r}
mortality_hb_2010_2021 %>% 
  ggplot()+
  aes(x = year, y = deaths_all_ages)+
  geom_col(fill = "light blue")+
  labs(
  title = "Death for all Cancer Types (2010 - 2021)",
  subtitle = "NHS Borders")+
  scale_x_continuous(name = "Year", breaks = c(2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019))+
  scale_y_continuous("Deaths (All ages)", limits = c(0,500), breaks = c(100,200,300,400, 500))
  
```


<h2> Waiting time 31 and 62 days

<br>

```{r}

wait_time_31 <- read_csv("data/Cancer Wait Time - 31 Day Standard.csv") %>% 
  clean_names()

wait_time_31

```
```{r}
wait_time_31_new <- wait_time_31 %>% 
  mutate(year  = case_when(quarter %in% c("2012Q1", "2012Q2", "2012Q3", "2012Q4") ~ 2012,
                           quarter %in% c("2013Q1", "2013Q2", "2013Q3", "2013Q4") ~ 2013,
                           quarter %in% c("2014Q1", "2014Q2", "2014Q3", "2014Q4") ~ 2014,
                           quarter %in% c("2015Q1", "2015Q2", "2015Q3", "2015Q4") ~ 2015,
                           quarter %in% c("2016Q1", "2016Q2", "2016Q3", "2016Q4") ~ 2016,
                           quarter %in% c("2017Q1", "2017Q2", "2017Q3", "2017Q4") ~ 2017,
                           quarter %in% c("2018Q1", "2018Q2", "2018Q3", "2018Q4") ~ 2018,
                           quarter %in% c("2019Q1", "2019Q2", "2019Q3", "2019Q4") ~ 2019,
                           quarter %in% c("2020Q1", "2020Q2", "2020Q3", "2020Q4") ~ 2020)
         , .after = "quarter") %>% 
  filter(hb == "S08000016",
         cancer_type == "All Cancer Types",
         hbt == "S08000016")

wait_time_31_new
  
```


```{r}
wait_31_1 <- wait_time_31_new %>% 
  group_by(year) %>% 
  summarise(count = sum(number_of_eligible_referrals31day_standard))
wait_31_1
```


<br>
YEAR VS number_of_eligible_referrals31day_standard


```{r}
wait_31_1 %>% 
  ggplot()+
  aes(x = year, y = count)+
  geom_col(fill = "blue")+
  labs(
  title = "Cancer Wait Time (31 day standard)",
  subtitle = "NHS Borders")
  
```

```{r}
wait_31_2 <- wait_time_31_new %>% 
  group_by(year) %>% 
  summarise(count = sum(number_of_eligible_referrals_treated_within31days))
wait_31_1
```
```{r}
wait_31_2 %>% 
  ggplot()+
  aes(x = year, y = count)+
  geom_col(fill = "blue")+
  labs(
  title = "Cancer Treatment Wait Time (31 day standard)",
  subtitle = "NHS Borders")
  
```

```{r}

wait_time_62 <- read_csv("data/Cancer Wait Time - 62 Day Standard.csv") %>% 
  clean_names()


wait_time_62_new <- wait_time_62 %>% 
  mutate(year  = case_when(quarter %in% c("2012Q1", "2012Q2", "2012Q3", "2012Q4") ~ 2012,
                           quarter %in% c("2013Q1", "2013Q2", "2013Q3", "2013Q4") ~ 2013,
                           quarter %in% c("2014Q1", "2014Q2", "2014Q3", "2014Q4") ~ 2014,
                           quarter %in% c("2015Q1", "2015Q2", "2015Q3", "2015Q4") ~ 2015,
                           quarter %in% c("2016Q1", "2016Q2", "2016Q3", "2016Q4") ~ 2016,
                           quarter %in% c("2017Q1", "2017Q2", "2017Q3", "2017Q4") ~ 2017,
                           quarter %in% c("2018Q1", "2018Q2", "2018Q3", "2018Q4") ~ 2018,
                           quarter %in% c("2019Q1", "2019Q2", "2019Q3", "2019Q4") ~ 2019,
                           quarter %in% c("2020Q1", "2020Q2", "2020Q3", "2020Q4") ~ 2020)
         , .after = "quarter") %>% 
  filter(hb == "S08000016",
         cancer_type == "All Cancer Types")

wait_time_62_new
  
```
```{r}
wait_62_1 <- wait_time_62_new %>% 
  group_by(year) %>% 
  summarise(count = sum(number_of_eligible_referrals62day_standard))
wait_62_1

wait_62_1 %>% 
  ggplot()+
  aes(x = year, y = count)+
  geom_col(fill = "blue")+
  labs(
  title = "Cancer Treatment Wait Time (62 day standard)",
  subtitle = "NHS Borders")

```

```{r}
wait_62_2 <- wait_time_62_new %>% 
  group_by(year) %>% 
  summarise(count = sum(number_of_eligible_referrals_treated_within62days))
wait_62_2

wait_62_2 %>% 
  ggplot()+
  aes(x = year, y = count)+
  geom_col(fill = "blue")+
  labs(
  title = "Cancer Treatment Wait Time (62 day standard)",
  subtitle = "NHS Borders")
```

